"""add AILog table

Revision ID: d0bb4af9209d
Revises: 2dc6dd791c8b
Create Date: 2026-02-28 03:57:25.545609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bb4af9209d'
down_revision = '2dc6dd791c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_logs_idea_id'), ['idea_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_logs_idea_id'))

    op.drop_table('ai_logs')
    # ### end Alembic commands ###
